title: About Aditya Shah
author: Aditya Shah
description: This site is about Aditya Shah
email: ashah1@ebnet.org
instagram_username: adityashah714
facebook_username: adityashah714

markdown: kramdown
theme: minima
